DIRS=testDir testDir2

all: one.txt

one.txt:
	for dir in ${DIRS}; do
		echo ${dir}
	done

# directories := ls -d */

#all:
#	for file in $(directories); do
#		echo $$file
#	done



#testDir/test.txt: test1.txt
#	cp -f test1.txt testDir/test.txt
